/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.util.ArrayList;
/**
 *
 * @author vince
 */
public class Fond extends javax.swing.JInternalFrame {

    /**
     * Creates new form Fond
     */
    public Fond(String titre, String sstitre, ArrayList donnees) {
        initComponents();
        
        this.setTitle(titre + " (" + sstitre + ")");
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.toFront();
        this.setSize(600, 400);
        
        if(sstitre=="Ajouter") {
             Fond_new nouveau = new Fond_new(donnees);
             this.setContentPane(nouveau);
            //pann.setVisible(true);  
        }
        else if(sstitre=="Consulter") {
             Fond_consult nouveau = new Fond_consult(donnees);
             this.setContentPane(nouveau);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
