/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;




/**
 *
 * @author vtorrese
 */
public class Utilisateur extends javax.swing.JInternalFrame {

    /**
     * Creates new form Utilisateur
     */
    
   
    
    public Utilisateur(String titre, String sstitre, ArrayList donnees) {
        initComponents();
        
        this.setTitle(titre + " (" + sstitre + ")");
        this.setClosable(true);
        this.setResizable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.toFront();
        this.setSize(600, 400);
       
        if(sstitre=="Nouvel utilisateur") {
               Utilisateur_new nouveau = new Utilisateur_new(donnees);
             this.setContentPane(nouveau);
            //pann.setVisible(true);  
        }
        else if(sstitre=="Voir profil") {
                Utilisateur_profil nouveau = new Utilisateur_profil(donnees);
                this.setContentPane(nouveau);
        }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
