/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.UtilisateurController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vince
 */
public class Utilisateur_profil extends javax.swing.JPanel {

        int status =0;
        int formation =0;
        int promotion =0;
        int site =0;
        String nom = "";
        
    public Utilisateur_profil(ArrayList donnees) {
        initComponents();
        
        //combobox status
        ArrayList status = new ArrayList();
        status = (ArrayList) donnees.get(0);
        Status_cherche.addItem("");
        Status_profil.addItem("");
        for(int i=0;i<status.size();i++) {
            ArrayList texte = (ArrayList) status.get(i);
            Status_cherche.addItem(texte.get(1).toString());
            Status_profil.addItem(texte.get(1).toString());
        }
        
        //combobox formation
        ArrayList formation = new ArrayList();
        formation = (ArrayList) donnees.get(3);
        Form_cherche.addItem("");
        Form_profil.addItem("");
        for(int i=0;i<formation.size();i++) {
            ArrayList texte = (ArrayList) formation.get(i);
            Form_cherche.addItem(texte.get(1).toString());
            Form_profil.addItem(texte.get(1).toString());
        }
        
        //combobox promotion
        ArrayList promotion = new ArrayList();
        promotion = (ArrayList) donnees.get(4);
        Promo_cherche.addItem("");
        Promo_profil.addItem("");
        for(int i=0;i<promotion.size();i++) {
            ArrayList texte = (ArrayList) promotion.get(i);
            Promo_cherche.addItem(texte.get(1).toString());
            Promo_profil.addItem(texte.get(1).toString());
        }
        
         //combobox site
        ArrayList site = new ArrayList();
        site = (ArrayList) donnees.get(1);
        Site_profil.addItem("");
        for(int i=0;i<site.size();i++) {
            ArrayList texte = (ArrayList) site.get(i);
            Site_profil.addItem(texte.get(1).toString());
        }
       
        //combobox civilite
        ArrayList civil = new ArrayList();
        civil = (ArrayList) donnees.get(2);
        Civil_profil.addItem("");
        for(int i=0;i<civil.size();i++) {
            ArrayList texte = (ArrayList) civil.get(i);
            Civil_profil.addItem(texte.get(1).toString());
        }
        
        //Tableau gauche des utilisateurs filtrés
        String  titre[] = {"ID","IDStatus","Status", "Nom", "Prénom", "Site"};
        initialiser_tableau();
        initialiser_panneau();
        ID_profil.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nom_cherche = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Form_cherche = new javax.swing.JComboBox<>();
        Promo_cherche = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Btn_valid = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Status_cherche = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab_user = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Status_profil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Nom_profil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Prenom_profil = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Site_profil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Adresse_profil = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Commune_profil = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CP_profil = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Tel_profil = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Form_profil = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        Promo_profil = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Mail_profil = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mdp_profil = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        Btn_modif = new javax.swing.JButton();
        Btn_supprimer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Civil_profil = new javax.swing.JComboBox<>();
        ID_profil = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tab_prt = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tab_res = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(900, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel2.setText("Nom");

        Nom_cherche.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Nom_cherche.setForeground(new java.awt.Color(153, 0, 153));
        Nom_cherche.setToolTipText("");
        Nom_cherche.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel7.setText("Formation");

        Form_cherche.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Form_cherche.setForeground(new java.awt.Color(153, 0, 153));

        Promo_cherche.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Promo_cherche.setForeground(new java.awt.Color(153, 0, 153));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel8.setText("Promotion");

        Btn_valid.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Btn_valid.setText("Valider");
        Btn_valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_validActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel10.setText("Statut");

        Status_cherche.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Status_cherche.setForeground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Form_cherche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Status_cherche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nom_cherche, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Promo_cherche, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_valid)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nom_cherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status_cherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Form_cherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Promo_cherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Btn_valid)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Form_cherche, Nom_cherche, Promo_cherche, Status_cherche});

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 12))); // NOI18N

        Tab_user.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Tab_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IDstatus", "Status", "Nom", "Prénom", "Site"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tab_user.getTableHeader().setReorderingAllowed(false);
        Tab_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tab_user);
        if (Tab_user.getColumnModel().getColumnCount() > 0) {
            Tab_user.getColumnModel().getColumn(0).setMinWidth(0);
            Tab_user.getColumnModel().getColumn(0).setPreferredWidth(0);
            Tab_user.getColumnModel().getColumn(0).setMaxWidth(0);
            Tab_user.getColumnModel().getColumn(1).setMinWidth(0);
            Tab_user.getColumnModel().getColumn(1).setPreferredWidth(0);
            Tab_user.getColumnModel().getColumn(1).setMaxWidth(0);
            Tab_user.getColumnModel().getColumn(2).setResizable(false);
            Tab_user.getColumnModel().getColumn(3).setResizable(false);
            Tab_user.getColumnModel().getColumn(4).setResizable(false);
            Tab_user.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profil", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 12))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/images/user.png"))); // NOI18N
        jLabel3.setText("photo");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel1.setText("Statut");

        Status_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Status_profil.setForeground(new java.awt.Color(153, 0, 153));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel4.setText("Nom");

        Nom_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Nom_profil.setForeground(new java.awt.Color(153, 0, 153));
        Nom_profil.setToolTipText("");
        Nom_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel5.setText("Prénom");

        Prenom_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Prenom_profil.setForeground(new java.awt.Color(153, 0, 153));
        Prenom_profil.setToolTipText("");
        Prenom_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel11.setText("Site");

        Site_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Site_profil.setForeground(new java.awt.Color(153, 0, 153));
        Site_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel6.setText("Adresse");

        Adresse_profil.setColumns(20);
        Adresse_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Adresse_profil.setForeground(new java.awt.Color(153, 0, 153));
        Adresse_profil.setRows(5);
        Adresse_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(Adresse_profil);

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel9.setText("Commune");

        Commune_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Commune_profil.setForeground(new java.awt.Color(153, 0, 153));
        Commune_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel12.setText("CP");

        CP_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        CP_profil.setForeground(new java.awt.Color(153, 0, 153));
        CP_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel13.setText("Tel");

        Tel_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Tel_profil.setForeground(new java.awt.Color(153, 0, 153));
        Tel_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel14.setText("Formation");

        Form_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Form_profil.setForeground(new java.awt.Color(153, 0, 153));

        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel15.setText("Promotion");

        Promo_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Promo_profil.setForeground(new java.awt.Color(153, 0, 153));

        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel16.setText("Mail/Login");

        Mail_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Mail_profil.setForeground(new java.awt.Color(153, 0, 153));
        Mail_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel17.setText("Mdp");

        mdp_profil.setText("jPasswordField1");

        Btn_modif.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Btn_modif.setText("Modifier");

        Btn_supprimer.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        Btn_supprimer.setForeground(new java.awt.Color(204, 0, 51));
        Btn_supprimer.setText("Supprimer");
        Btn_supprimer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/images/mail.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(60, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));

        jLabel18.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jLabel18.setText("Civilité");

        Civil_profil.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        Civil_profil.setForeground(new java.awt.Color(153, 0, 153));
        Civil_profil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tab_prt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre", "Statut", "Date retour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Tab_prt);
        if (Tab_prt.getColumnModel().getColumnCount() > 0) {
            Tab_prt.getColumnModel().getColumn(0).setResizable(false);
            Tab_prt.getColumnModel().getColumn(1).setResizable(false);
            Tab_prt.getColumnModel().getColumn(2).setResizable(false);
        }

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField1.setText("Historique des prêts");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField2.setText("Réservations");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        Tab_res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre", "Statut", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Tab_res);
        if (Tab_res.getColumnModel().getColumnCount() > 0) {
            Tab_res.getColumnModel().getColumn(0).setResizable(false);
            Tab_res.getColumnModel().getColumn(1).setResizable(false);
            Tab_res.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tel_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CP_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Commune_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Promo_profil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Form_profil, 0, 152, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Mail_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mdp_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_supprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_modif))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Prenom_profil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Status_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18))
                                    .addComponent(Nom_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Civil_profil, 0, 60, Short.MAX_VALUE)
                                    .addComponent(ID_profil))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Site_profil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Nom_profil, Prenom_profil, Status_profil, jScrollPane2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Site_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Status_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(Nom_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Prenom_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Civil_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ID_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Commune_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(Form_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CP_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(Promo_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Tel_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Mail_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(mdp_profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_modif)
                        .addComponent(Btn_supprimer)))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Nom_profil, Prenom_profil, Status_profil});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CP_profil, Mail_profil, Tel_profil, mdp_profil});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Btn_modif, Btn_supprimer});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_validActionPerformed
        
        //Controles saisies
        if(Status_cherche.getSelectedIndex()==0 && Nom_cherche.getText().equals("") && Form_cherche.getSelectedIndex()==0 && Promo_cherche.getSelectedIndex()==0)  {
            JOptionPane.showMessageDialog(this,"Filtre invalide !");}
        else {
            status = Status_cherche.getSelectedIndex();
            formation = Form_cherche.getSelectedIndex();
            promotion = Promo_cherche.getSelectedIndex();
            nom = Nom_cherche.getText();
            ArrayList tabresult = new ArrayList();
            //ArrayList tabresult = UtilisateurController.chercheUser(status,nom,formation,promotion);
            tabresult = (ArrayList) UtilisateurController.chercheUser(status,nom,formation,promotion);
            initialiser_tableau();
            //System.out.println(tabresult.size());
            DefaultTableModel model = (DefaultTableModel) Tab_user.getModel();
            
              for(int i=0;i<tabresult.size();i++) {
                    ArrayList tab = (ArrayList) tabresult.get(i);
                  //System.out.println(tab.get(0));
                  model.addRow(new Object[]{tab.get(0), tab.get(9), tab.get(10), tab.get(1), tab.get(2),tab.get(12)});
            }
           
            
               
            
        }
    }//GEN-LAST:event_Btn_validActionPerformed

    private void Tab_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_userMouseClicked
            
        //Sélection d'une ligne de la tab_user
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            String iduser = Tab_user.getValueAt(row,0).toString();
            String idstatus = Tab_user.getValueAt(row,1).toString();
            
        //Récupération des données
            ArrayList profil = (ArrayList) UtilisateurController.chercheUserById(iduser,idstatus).get(0);
            ArrayList pret = (ArrayList) UtilisateurController.cherchePrtByUser(iduser);
            
            
        //Affichage des données sur le panneau profil    
            initialiser_panneau();
            Civil_profil.setSelectedIndex(Integer.parseInt(profil.get(13).toString()));
            Status_profil.setSelectedIndex(Integer.parseInt(profil.get(9).toString()));
            ID_profil.setText(profil.get(0).toString());
            Nom_profil.setText(profil.get(1).toString());
            Prenom_profil.setText(profil.get(2).toString());
            Adresse_profil.setText(profil.get(4).toString());
            Site_profil.setSelectedIndex(Integer.parseInt(profil.get(11).toString()));
            if(Integer.parseInt(profil.get(9).toString())==2) {
                Form_profil.setSelectedIndex(Integer.parseInt(profil.get(15).toString()));
                Promo_profil.setSelectedIndex(Integer.parseInt(profil.get(17).toString()));
            }
            Commune_profil.setText(profil.get(6).toString());
            CP_profil.setText(profil.get(5).toString());
            Tel_profil.setText(profil.get(7).toString());
            Mail_profil.setText(profil.get(8).toString());
            
         //Remplissage des tables tab_prt et tab_res
           DefaultTableModel model = (DefaultTableModel) Tab_prt.getModel();
            for(int i=0;i<pret.size();i++) {
                    ArrayList tab = (ArrayList) pret.get(i);
                     
                    if(tab.get(4).toString()=="1") {
                        
                    }
                    else if (tab.get(4).toString()=="2") {
                        
                    }
               
                    
                    model.addRow(new Object[]{tab.get(7),tab.get(5),tab.get(1)});
                    
            }
            
            
    }//GEN-LAST:event_Tab_userMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    public void initialiser_tableau() {
                  DefaultTableModel model = (DefaultTableModel) Tab_user.getModel();
                   model.setRowCount(0);
                }

    public void initialiser_panneau() {
        Status_profil.setSelectedIndex(0);
        Civil_profil.setSelectedIndex(0);
        Site_profil.setSelectedIndex(0);
        Form_profil.setSelectedIndex(0);
        Promo_profil.setSelectedIndex(0);
        Nom_profil.setText("");
        Prenom_profil.setText("");
        Adresse_profil.setText("");
        Commune_profil.setText("");
        CP_profil.setText("");
        Tel_profil.setText("");
        Mail_profil.setText("");
        mdp_profil.setColumns(15);
        mdp_profil.setText("");
       DefaultTableModel pret = (DefaultTableModel) Tab_prt.getModel();
       pret.setRowCount(0);
       DefaultTableModel resa = (DefaultTableModel) Tab_res.getModel();
       resa.setRowCount(0);
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Adresse_profil;
    private javax.swing.JButton Btn_modif;
    private javax.swing.JButton Btn_supprimer;
    private javax.swing.JButton Btn_valid;
    private javax.swing.JTextField CP_profil;
    private javax.swing.JComboBox<String> Civil_profil;
    private javax.swing.JTextField Commune_profil;
    private javax.swing.JComboBox<String> Form_cherche;
    private javax.swing.JComboBox<String> Form_profil;
    private javax.swing.JTextField ID_profil;
    private javax.swing.JTextField Mail_profil;
    private javax.swing.JTextField Nom_cherche;
    private javax.swing.JTextField Nom_profil;
    private javax.swing.JTextField Prenom_profil;
    private javax.swing.JComboBox<String> Promo_cherche;
    private javax.swing.JComboBox<String> Promo_profil;
    private javax.swing.JComboBox<String> Site_profil;
    private javax.swing.JComboBox<String> Status_cherche;
    private javax.swing.JComboBox<String> Status_profil;
    private javax.swing.JTable Tab_prt;
    private javax.swing.JTable Tab_res;
    private javax.swing.JTable Tab_user;
    private javax.swing.JTextField Tel_profil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField mdp_profil;
    // End of variables declaration//GEN-END:variables
}
